# Generated by Django 5.0.6 on 2024-07-03 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_productagehair_productdan_productfall_productfri'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Productfall',
            new_name='Productperfumes',
        ),
    ]
