# Generated by Django 5.0.6 on 2024-07-04 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_productbath'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='qunatity',
            new_name='quantity',
        ),
    ]
