# Generated by Django 5.0.6 on 2024-07-05 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_qunatity_orderitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='productage',
            name='price',
        ),
        migrations.RemoveField(
            model_name='productagehair',
            name='price',
        ),
        migrations.RemoveField(
            model_name='productbath',
            name='price',
        ),
        migrations.RemoveField(
            model_name='productdan',
            name='price',
        ),
        migrations.RemoveField(
            model_name='productdark',
            name='price',
        ),
        migrations.RemoveField(
            model_name='productfri',
            name='price',
        ),
        migrations.RemoveField(
            model_name='productperfumes',
            name='price',
        ),
        migrations.RemoveField(
            model_name='producttan',
            name='price',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]
